<a href="https://colab.research.google.com/github/jumorap/AlgorithmsUN2021II/blob/main/Lab_1/Jumorap_QuanconnectTutortials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img alt="UN logo" height="80px" src="https://unal.edu.co/typo3conf/ext/unal_skin_default/Resources/Public/images/escudoUnal_black.png" align="right">


<H1 align="center">QuantConnect: Introduction to Financial Python:</H1>
<h3 align="center">Juan Camilo Mora Pulido</h3>
<h3 align="center">G.1. Algoritmos</h3>
<h3 align="center">Prof. Germán Jairo Hernández Pérez</h3>
<h4 align="center">Depto. de Ing.a de Sistemas e Industrial</h4>
<h5 align="center">Fac. Ingeniería</h5>
<h5 align="center">UNIVERSIDAD NACIONAL DE COLOMBIA</h5>

Course Rel. [QuantConnect: Introduction to Financial Python](https://www.quantconnect.com/tutorials/introduction-to-financial-python/data-types-and-data-structures)


___

#*1. Data Types and Data Structures*

###**Introduction**
This tutorial provides a basic introduction to the Python programming language. If you are new to Python, you should run the code snippets while reading this tutorial. If you are an advanced Python user, please feel free to skip this chapter.

###**Basic Variable Types**
The basic types of variables in Python are: strings, integers, floating point numbers and booleans.

Strings in python are identified as a contiguous set of characters represented in either single quotes (' ') or double quotes (" ").

In [223]:
# QuantConnect example
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [224]:
# My example
my_string1 = 'Hello, my name is'
my_string2 = "Juan"
print(my_string1 + ' ' + my_string2)

# Or we can use a string format as f
my_string1 = 'Hello, my name is'
my_string2 = "Juan"
print(f'{my_string1} {my_string2}')

Hello, my name is Juan
Hello, my name is Juan


An integer is a round number with no values after the decimal point.

In [225]:
# QuantConnect example
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [226]:
# My example
my_int = 12345
print(f'The numer: {my_int} is a variable of type: {type(my_int)}')

The numer: 12345 is a variable of type: <class 'int'>


The built-in function int() can convert a string into an integer.


In [227]:
# QuantConnect example
my_string = "100"
print(type(my_string))

my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [228]:
# My example
my_string = "100"
print(f'{my_string} is a variable of type {type(my_string)}')

my_int = int(my_string)
print(f'But with the function int({my_int}) is a variable of type {type(my_int)}')

100 is a variable of type <class 'str'>
But with the function int(100) is a variable of type <class 'int'>


A floating point number, or a float, is a real number in mathematics. In Python we need to include a value after a decimal point to define it as a float.



In [229]:
# QuantConnect example
my_float = 1.0
print(type(my_float))

my_int = 1
print(type(my_int))

<class 'float'>
<class 'int'>


In [230]:
# My example
my_float = 1.0
print(f'{my_float} is \t{type(my_float)}')

my_int = 1
print(f'{my_int} is \t{type(my_int)}')

1.0 is 	<class 'float'>
1 is 	<class 'int'>


As you can see above, if we don't include a decimal value, the variable would be defined as an integer. The built-in function float() can convert a string or an integer into a float.



In [231]:
# QuantConnect example
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [232]:
# My example
my_string = "100"
my_float = float(my_string)
print(f'Using the function float({my_string}), now the variable is {type(my_float)}')

Using the function float(100), now the variable is <class 'float'>


A boolean, or bool, is a binary variable. Its value can only be True or False. It is useful when we do some logic operations, which would be covered in our next chapter.



In [233]:
# QuantConnect example
my_bool = False
print(my_bool)
print(type(my_bool))

False
<class 'bool'>


In [234]:
# My example
my_bool = False
print(f'my_bool = {my_bool} is a variable of type {type(my_bool)}')

my_bool = False is a variable of type <class 'bool'>


##*Basic Math Operations*
The basic math operators in python are demonstrated below:

In [235]:
# QuantConnect example
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [236]:
# My example
print("Addition \t", 10 + 5)
print("Subtraction \t", 8 - 2)
print("Multiplication \t", 7 * 4)
print("Division \t", 20 / 2)
print("Exact division \t", 20 // 2)
print("Exponent \t", 5 ** 2)

Addition 	 15
Subtraction 	 6
Multiplication 	 28
Division 	 10.0
Exact division 	 10
Exponent 	 25


##*Data Collections*
####**List**

A list is an ordered collection of values. A list is mutable, which means you can change a list's value without changing the list itself. Creating a list is simply putting different comma-separated values between square brackets.

In [237]:
# QuantConnect example
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [238]:
# My example
my_list = ['This', 'is', 'my', 'list', 1, 2, 3, 'testing...']
print(my_list)

['This', 'is', 'my', 'list', 1, 2, 3, 'testing...']


The values in a list are called "elements". We can access list elements by indexing. Python index starts from 0. So if you have a list of length n, the index of the first element will be 0, and that of the last element will be n − 1. By the way, the length of a list can be obtained by the built-in function len().



In [239]:
# QuantConnect example
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

5
Quant
3


In [240]:
# My example
my_list = ['I`m first', 'This won`t appear', 1, 2, 3]
print(f'List length: {len(my_list)}')
print(f'First element: {my_list[0]}')
print(f'Last element: {my_list[-1]}')

List length: 5
First element: I`m first
Last element: 3


You can also change the elements in the list by accessing an index and assigning a new value.



In [241]:
# QuantConnect example
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [242]:
# My example
my_list = ['I`m first', 'This won`t appear', 1, 2, 3]
print(f'Before:\t{my_list}')

my_list[1] = 'I appear'
print(f'After: \t{my_list}')

Before:	['I`m first', 'This won`t appear', 1, 2, 3]
After: 	['I`m first', 'I appear', 1, 2, 3]


A list can also be sliced with a colon:



In [243]:
# QuantConnect example
my_list = ['Quant','Connect',1,2,3]
print(my_list[1: 3])

['Connect', 1]


In [244]:
# My example
my_list = ['I`m first', 'This will appear', 1, 2, 3]
print(my_list[1: -2])

['This will appear', 1]


The slice starts from the first element indicated, but excludes the last element indicated. Here we select all elements starting from index 1, which refers to the second element:



In [245]:
print(my_list[1:])

['This will appear', 1, 2, 3]


And all elements up to but excluding index 3:

In [246]:
print(my_list[:3])

['I`m first', 'This will appear', 1]


If you wish to add or remove an element from a list, you can use the append() and remove() methods for lists as follows:



In [247]:
# QuantConnect example
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)

my_list.remove('Hello')
print(my_list)

['Hello', 'Quant', 'Hello']
['Quant', 'Hello']


In [248]:
# My example
my_list = ['First', 'Second']

my_list.append('I`ll disapear')
print(my_list)

my_list.remove('I`ll disapear')
print(my_list)

['First', 'Second', 'I`ll disapear']
['First', 'Second']


When there are repeated instances of "Hello", the first one is removed.

####**Tuple**
A tuple is a data structure type similar to a list. The difference is that a tuple is immutable, which means you can't change the elements in it once it's defined. We create a tuple by putting comma-separated values between parentheses.



In [249]:
my_tuple = ('Welcome','to','QuantConnect')

Just like a list, a tuple can be sliced by using index.



In [250]:
# QuantConnect example
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [251]:
# My example
my_tuple = ('Hello, ','I`m','inmutable')
print(my_tuple[1:])

('I`m', 'inmutable')


####**Set**
A set is an unordered collection with no duplicate elements. The built-in function set() can be used to create sets.



In [252]:
# QuantConnect example
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'GOOG', 'FB', 'AAPL', 'IBM', 'F'}


In [253]:
# My example
stock_list = ['A','B','C','D','E']
stock_set = set(stock_list)
print(stock_set)

{'C', 'D', 'A', 'B', 'E'}


Set is an easy way to remove duplicate elements from a list.

###**Dictionary**
A dictionary is one of the most important data structures in Python. Unlike sequences which are indexed by integers, dictionaries are indexed by keys which can be either strings or floats.

A dictionary is an unordered collection of key : value pairs, with the requirement that the keys are unique. We create a dictionary by placing a comma-separated list of key : value pairs within the braces.

In [254]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}

After defining a dictionary, we can access any value by indicating its key in brackets.



In [255]:
print(my_dic['GOOG'])

Alphabet


We can also change the value associated with a specified key:



In [256]:
# QuantConnect example
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [257]:
# My example
print(f"Before:\t{my_dic['AAPL']}")
my_dic['AAPL'] = 'Apple Computers'
print(f"After: \t{my_dic['AAPL']}")

Before:	Apple
After: 	Apple Computers


The built-in method of the dictionary object dict.keys() returns a list of all the keys used in the dictionary.



In [258]:
print(my_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


###**Common String Operations**
A string is an immutable sequence of characters. It can be sliced by index just like a tuple:



In [259]:
# QuantConnect example
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [260]:
# My example
my_str = 'I won`t appear, but I`ll appear'
print(my_str[20:])

I`ll appear


There are many methods associated with strings. We can use string.count() to count the occurrences of a character in a string, use string.find() to return the index of a specific character, and use string.replace() to replace characters.



In [261]:
print("Counting the number of e's in this sentence".count('e'))
print('The first time e appears in this sentence'.find('e'))
print('all the a in this sentence now becomes e'.replace('a','e'))

6
2
ell the e in this sentence now becomes e


The most commonly used method for strings is string.split(). This method will split the string by the indicated character and return a list:



In [262]:
# QuantConnect example
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

hour = time.split(':')[0]
print(hour)

2016-04-01 09:43:00
09


In [263]:
# My example
fullname = 'Linus Benedict Torvalds'
splited_list = fullname.split(' ')
firstname = splited_list[0]
lastname = splited_list[2]
print("Name:", firstname, lastname)

Name: Linus Torvalds


We can replace parts of a string by our variable. This is called string formatting.



In [264]:
# QuantConnect example
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [265]:
# My example
my_time = 'Hour: {}, Minute: {}'.format(12, 21)
print(my_time)

# Is posiible print formated text with the reference f'{}'
my_time = f'Hour: {5}, Minute: {30}'
print(my_time)

Hour: 12, Minute: 21
Hour: 5, Minute: 30


Another way to format a string is to use the % symbol.



In [266]:
print('pi is %f' % 3.14)
print('%s to %s' % ('Welcome', 'QuantConnect'))

pi is 3.140000
Welcome to QuantConnect


In [267]:
print('e is %f' % 2.71828182846)
print('%s for %s' % ('Thanks', 'Read'))

e is 2.718282
Thanks for Read


%s is a placeholder that takes in a string. Similarly %f takes a float and %d takes an integer.

###**Summary**
We have seen the basic data types and data structures in Python. It's important to keep practicing to become familiar with these data structures. In the next tutorial, we will cover for and while loops and logical operations in Python.

#*2. Logical Operations and Loops*

###**Introduction**
We discussed the basic data types and data structures in Python in the last tutorial. This chapter covers logical operations and loops in Python, which are very common in programming.

###**Logical Operations**
Like most programming languages, Python has comparison operators:


In [268]:
# QuantConnect example
print(1 == 0)    # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)    # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [269]:
# My example
print(1 == "0")
print("1" == "1")
print(1 != 1)
print(10 >= 5)
print(1 > 2)

False
True
False
True
False


Each statement above has a boolean value, which must be either True or False, but not both.

We can combine simple statements P and Q to form complex statements using logical operators:

* The statement "P and Q" is true if both P and Q are true, otherwise it is false.
* The statement "P or Q" is false if both P and Q are false, otherwise it is true.
* The statement "not P" is true if P is false, and vice versa.

In [270]:
# QuantConnect example
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2)
print(2 > 1 or  3 < 2)
print(2 < 1 and 3 < 2)

True
False
True
False


In [271]:
# My example
print(1 >= 1 and 1 > 2)
print(5 >= 10 and 3 < 2)
print(2 <= 1 or  3 < 2)
print(2 < 10 and 3 < 5)

False
False
False
True


When dealing with a very complex logical statement that involves in several statements, we can use brackets to separate and combine them.



In [272]:
print((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

False
True


Comparing the above two statements, we can see that it's wise to use brackets when we make a complex logical statement.

###**If Statement**
An if statement executes a segment of code only if its condition is true. A standard if statement consists of 3 segments: if, elif and else.

```py
if condition1:
    # if condition1 is true, execute the code here
    # and ignore the rest of this if statement
elif condition2:
    # if condition1 is false, and condition2 is true, execute the code here
    # and ignore the rest of this if statement
else:
    # if none of the above conditions is True, execute the code here
```
An if statement doesn't necessarily has elif and else part. If it's not specified, the indented block of code will be executed when the condition is true, otherwise the whole if statement will be skipped.



In [273]:
# QuantConnect example
i = 0
if i == 0: print('i == 0 is True')

i == 0 is True


In [274]:
# My example
i = 5
if i != 0: print(f'i == 5 is {i == 5}')

i == 5 is True


As we mentioned above, we can write some complex statements here:



In [275]:
# QuantConnect example
p = 1 > 0
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

q is false


In [276]:
# My example
p = 1 > 10
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

None of p and q is true


###**Loop Structure**
Loops are an essential part of programming. The "for" and "while" loops run a block of code repeatedly.

####**While Loop**
A "while" loop will run repeatedly until a certain condition has been met.

In [277]:
# QuantConnect example
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [278]:
# My example
i = 0

while i < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9


When making a while loop, we need to ensure that something changes from iteration to iteration so that the while loop will terminate, otherwise, it will run forever. Here we used i += 1 (short for i = i + 1) to make i larger after each iteration. This is the most commonly used method to control a while loop.

####**For Loop**
A "for" loop will iterate over a sequence of value and terminate when the sequence has ended.

In [279]:
# QuantConnect example
for x in [1,2,3,4,5]: print(x)

1
2
3
4
5


In [280]:
# My example
for x in range(10): 
    print(x)

0
1
2
3
4
5
6
7
8
9


We can also add if statements in a for loop. Here is a real example from our pairs trading algorithm:



In [281]:
# QuantConnect example
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [282]:
# My example
full_letter_set = ['A','B','C','D','E']
selected = ['C','D']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(f'Full list: \t\t{full_letter_set}')
print(f'Selected: \t\t{new_list}')
print(f'Without selected: \t{new_list}')

Full list: 		['A', 'B', 'C', 'D', 'E']
Selected: 		['AAPL', 'GOOG', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
Without selected: 	['AAPL', 'GOOG', 'IBM', 'FB', 'F', 'V', 'G', 'GE']


Here we iterated all the elements in the list 'stocks'. Later in this chapter, we will introduce a smarter way to do this, which is just a one-line code.

####**Break and continue**
These are two commonly used commands in a for loop. If "break" is triggered while a loop is executing, the loop will terminate immediately:

In [283]:
# QuantConnect example
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print(stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [284]:
# My example
for i in range(10):
    print(i)
    if i == 8: break

0
1
2
3
4
5
6
7
8


The "continue" command tells the loop to end this iteration and skip to the next iteration:



In [285]:
# QuantConnect example
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print(stock)

AAPL
GOOG
IBM
F
V
G
GE


In [286]:
# My example
for i in range(10):
    if i % 2 ==0 : continue
    print(i)

1
3
5
7
9


###**List Comprehension**
List comprehension is a Pythonic way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence. For example, if we want to create a list of squares using for loop:

In [287]:
# QuantConnect example
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


In [288]:
# My example
squares = []
for i in range(10):
    squares.append(i**2)
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Using list comprehension:



In [289]:
# QuantConnect example
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print(squares)

[1, 4, 9, 16, 25]


In [290]:
# My example
squares = [x ** 2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Recall the example above where we used a for loop to select stocks. Here we use list comprehension:

In [291]:
# QuantConnect example
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [292]:
# My example
letters = ['A','B','C','D','E','F', 'G', 'H']
selected = ['C','D']
new_list = [x for x in letters if x not in selected]
print(new_list)

['A', 'B', 'E', 'F', 'G', 'H']


A list comprehension consists of square brackets containing an expression followed by a "for" clause, and possibly "for" or "if" clauses. For example:



In [293]:
# QuantConnect example
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [294]:
# My example
print([(x, y) for x in range(5) for y in range(4)])
print([(x, y) for x in range(5) for y in range(4) if x % 2 == 0 and y % 2 == 0])

[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3), (4, 0), (4, 1), (4, 2), (4, 3)]
[(0, 0), (0, 2), (2, 0), (2, 2), (4, 0), (4, 2)]


List comprehension is an elegant way to organize one or more for loops when creating a list.

###**Summary**
This chapter has introduced logical operations, loops, and list comprehension. In the next chapter, we will introduce functions and object-oriented programming, which will enable us to make our codes clean and versatile.

#*3. Functions and Objective-Oriented Programming*
###**Introduction**
In the last tutorial we introduced logical operations, loops and list comprehension. We will introduce functions and object-oriented programming in this chapter, which will enable us to build complex algorithms in more flexible ways.

###**Functions**
A function is a reusable block of code. We can use a function to output a value, or do anything else we want. We can easily define our own function by using the keyword "def".

In [295]:
# QuantConnect example
def product(x,y):
    return x*y
print(product(2,3))

6


In [296]:
# My example
def plus(x, y):
    return x + y

print(plus(5, 10))

15


The keyword "def" is followed by the function name and the parenthesized list of formal parameters. The statements that form the body of the function start at the next line, and must be indented. The product() function above has "x" and "y" as its parameters. A function doesn't necessarily have parameters:



In [297]:
# QuantConnect example
def say_hi():
    print("Welcome to QuantConnect")
say_hi()

Welcome to QuantConnect


In [298]:
# My example
def say_hi():
    print("Hello, World!")

say_hi()

Hello, World!


###**Built-in Function**
range() is a function that creates a list containing an arithmetic sequence. It's often used in for loops. The arguments must be integers. If the "step" argument is omitted, it defaults to 1.

In [299]:
print(range(10))
print(range(1, 11))
print(range(1, 11, 2))

range(0, 10)
range(1, 11)
range(1, 11, 2)


len() is another function used together with range() to create a for loop. This function returns the length of an object. The argument must be a sequence or a collection.



In [300]:
# QuantConnect example
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [301]:
# My example
tickers = ['A', 'B', 'C', 'D', 'E', 'F']
len_tickers = len(tickers)
print(f"The number of tickers is {len_tickers}")
for k in range(len_tickers):
    print(k + 1, tickers[k])

The number of tickers is 6
1 A
2 B
3 C
4 D
5 E
6 F


*Note: If you want to print only the tickers without those numbers, then simply write "for ticker in tickers: print ticker"*

map() is a function that applies a specific function to every item of a sequence or collection, and returns a list of the results.

In [302]:
# QuantConnect example
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [303]:
# My example
tickers = ['Hello', 'this', 'message', 'used', 'scissors']
print(list(map(len, tickers)))

[5, 4, 7, 4, 8]


The lambda operator is a way to create small anonymous functions. These functions are just needed where they have been created. For example:



In [304]:
list(map(lambda x: x ** 2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

map() can be applied to more than one list. The lists have to have the same length.



In [305]:
list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1]))

[6, 6, 6, 6, 6]

sorted() takes a list or set and returns a new sorted list:


In [306]:
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

We can add a "key" parameter to specify a function to be called on each list element prior to making comparisons. For example:



In [307]:
# QuantConnect example
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [308]:
# My example
letter_numb = [('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E', 5)]
sorted(letter_numb, key = lambda x: x[1])

[('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E', 5)]

By default the values are sorted by ascending order. We can change it to descending by adding an optional parameter "reverse'.



In [309]:
# QuantConnect example
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [310]:
# My example
letter_numb = [('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E', 5)]
sorted(letter_numb, key = lambda x: x[1], reverse = True)

[('E', 5), ('D', 4), ('C', 3), ('B', 2), ('A', 1)]

Lists also have a function list.sort(). This function takes the same "key" and "reverse" arguments as sorted(), but it doesn't return a new list.



In [311]:
# QuantConnect example
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [312]:
# My example
letter_numb = [('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E', 5)]
letter_numb.sort(key = lambda x: x[1])
print(letter_numb)

[('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E', 5)]


###**Object-Oriented Programming**
Python is an object-oriented programming language. It's important to understand the concept of "objects" because almost every kind of data from QuantConnect API is an object.

####**Class**
A class is a type of data, just like a string, float, or list. When we create an object of that data type, we call it an instance of a class.

In Python, everything is an object - everything is an instance of some class. The data stored inside an object are called attributes, and the functions which are associated with the object are called methods.

For example, as mentioned above, a list is an object of the "list" class, and it has a method list.sort().

We can create our own objects by defining a class. We would do this when it's helpful to group certain functions together. For example, we define a class named "Stock" here:

In [313]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)

The "Stock" class has attributes "ticker", "open", "close", "volume" and "rate_return". Inside the class body, the first method is called __init__, which is a special method. When we create a new instance of the class, the __init__ method is immediately executed with all the parameters that we pass to the "Stock" object. The purpose of this method is to set up a new "Stock" object using data we have provided.

Here we create two Stock objects named "apple" and "google".

In [314]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

Stock objects also have two other methods: update() and print_return(). We can access the attribues of a Stock object and call its methods:



In [315]:
apple.ticker

google.print_return()

google.update(912.8, 913.4)
google.print_return()

0.014465338822744034
0.0006573181419806673


By calling the update() function, we updated the open and close prices of a stock. Please note that when we use the attributes or call the methods inside a class, we need to specify them as self.attribute or self.method(), otherwise Python will deem them as global variables and thus raise an error.

We can add an attribute to an object anywhere:

In [316]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

We can check what names (i.e. attributes and methods) are defined on an object using the dir() function:



In [317]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

###**Inheritance**
Inheritance is a way of arranging classes in a hierarchy from the most general to the most specific. A "child" class is a more specific type of a "parent" class because a child class will inherit all the attribues and methods of its parent. For example, we define a class named "Child" which inherits "Stock":

In [318]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

Then we create an object:



In [319]:
aa = Child('AA')
print(aa.name)

aa.update(100, 102)
print(aa.open)

print(aa.close)

print(aa.print_return())


AA
100
102
0.020000000000000018
None


As seen above, the new class Child has inherited the methods from Stock.
###**Summary**
In this chapter we have introduced functions and classes. When we write a QuantConnect algorithm, we would define our algorithm as a class (QCAlgorithm). This means our algorithm inherited the QC API methods from QCAlgorithm class.

In the next chapter, we will introduce NumPy and Pandas, which enable us to conduct scientific calculations in Python.

#*4. NumPy and Basic Pandas*
###**Introduction**
Now that we have introduced the fundamentals of Python, it's time to learn about NumPy and Pandas.

###**NumPy**
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also has strong integration with Pandas, which is another powerful tool for manipulating financial data.

Python packages like NumPy and Pandas contain classes and methods which we can use by importing the package:

In [320]:
import numpy as np

###**Basic NumPy Arrays**
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. Here we make an array by passing a list of Apple stock prices:

In [321]:
# QuantConnect example
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [322]:
# My example
price_list = [123.456, 789.101, 112.131, 415.161]
price_array = np.array(price_list)
print(price_array, type(price_array))

[123.456 789.101 112.131 415.161] <class 'numpy.ndarray'>


Notice that the type of array is "ndarray" which is a multi-dimensional array. If we pass np.array() a list of lists, it will create a 2-dimensional array.



In [323]:
# QuantConnect example
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [324]:
# My example
Ar = np.array([[1, 3, 4], [5, 6, 7], [8, 9, 10]])
print(Ar, type(Ar))

[[ 1  3  4]
 [ 5  6  7]
 [ 8  9 10]] <class 'numpy.ndarray'>


We get the dimensions of an ndarray using the .shape attribute:



In [325]:
print(Ar.shape)

(3, 3)


If we create an 2-dimensional array (i.e. matrix), each row can be accessed by index:



In [326]:
print(Ar[0])

print(Ar[1])

[1 3 4]
[5 6 7]


If we want to access the matrix by column instead:



In [327]:
print('First column:', Ar[:, 0])

print('Second column:', Ar[:, 1])

First column: [1 5 8]
Second column: [3 6 9]


####**Array Functions**
Some functions built in NumPy that allow us to perform calculations on arrays. For example, we can apply the natural logarithm to each element of an array:

In [328]:
np.log(price_array)

array([4.81588482, 6.67089432, 4.71966783, 6.0286664 ])

Other functions return a single value:



In [329]:
np.mean(price_array)

print(np.std(price_array))

print(np.sum(price_array))

print(np.max(price_array))

275.9359090073046
1439.8490000000002
789.101


The functions above return the mean, standard deviation, total and maximum value of an array.

###**Pandas**
Pandas is one of the most powerful tools for dealing with financial data. First we need to import Pandas:

In [330]:
import pandas as pd

#####**Series**
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, float, Python object, etc.)

We create a Series by calling pd.Series(data), where data can be a dictionary, an array or just a scalar value.

In [331]:
# QuantConnect example
price_quant = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price_quant)
print(s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [332]:
# My example
price = [123.456, 789.101, 112.131, 415.161, 718.192, 212.223]
s = pd.Series(price)
print(s)

0    123.456
1    789.101
2    112.131
3    415.161
4    718.192
5    212.223
dtype: float64


We can customize the indices of a new Series:



In [333]:
# QuantConnect example
s = pd.Series(price_quant, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [334]:
# My example
s = pd.Series(price, index = ['A', 'B', 'C', 'D', 'E', 'F'])
print(s)

A    123.456
B    789.101
C    112.131
D    415.161
E    718.192
F    212.223
dtype: float64


Or we can change the indices of an existing Series:



In [335]:
s.index = [6,5,4,3,2,1]
print(s)

6    123.456
5    789.101
4    112.131
3    415.161
2    718.192
1    212.223
dtype: float64


Series is like a list since it can be sliced by index:



In [336]:
print(s[1:])
print(s[:-2])

5    789.101
4    112.131
3    415.161
2    718.192
1    212.223
dtype: float64
6    123.456
5    789.101
4    112.131
3    415.161
dtype: float64


Series is also like a dictionary whose values can be set or fetched by index label:



In [337]:
print(s[4])
s[4] = 0
print(s)

112.131
6    123.456
5    789.101
4      0.000
3    415.161
2    718.192
1    212.223
dtype: float64


Series can also have a name attribute, which will be used when we make up a Pandas DataFrame using several series.



In [338]:
s = pd.Series(price, name = 'Apple Prices')
print(s)
print(s.name)

0    123.456
1    789.101
2    112.131
3    415.161
4    718.192
5    212.223
Name: Apple Prices, dtype: float64
Apple Prices


We can get the statistical summaries of a Series:



In [339]:
print(s.describe())

count      6.000000
mean     395.044000
std      299.109869
min      112.131000
25%      145.647750
50%      313.692000
75%      642.434250
max      789.101000
Name: Apple Prices, dtype: float64


####**Time Index**
Pandas has a built-in function specifically for creating date indices: pd.date_range(). We use it to create a new index for our Series:

In [341]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    123.456
2017-01-02    789.101
2017-01-03    112.131
2017-01-04    415.161
2017-01-05    718.192
2017-01-06    212.223
Freq: D, Name: Apple Prices, dtype: float64


Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:

In [343]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    123.456
5    789.101
4    112.131
3    415.161
2    718.192
1    212.223
Name: Apple Prices, dtype: float64
212.223


If we intended to take the second element of the series, we would make a mistake here, because the index are integers. In order to access to the element we want, we use iloc[] here:



In [344]:
print(s.iloc[1])

789.101


While working with time series data, we often use time as the index. Pandas provides us with various methods to access the data by time index.



In [345]:
s.index = time_index
print(s['2017-01-03'])

112.131


We can even access to a range of dates:



In [346]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    789.101
2017-01-03    112.131
2017-01-04    415.161
2017-01-05    718.192
Freq: D, Name: Apple Prices, dtype: float64


Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:



In [347]:
print(s[s < np.mean(s)])
print(s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    123.456
2017-01-03    112.131
2017-01-06    212.223
Name: Apple Prices, dtype: float64
2017-01-02    789.101
2017-01-04    415.161
2017-01-05    718.192
Name: Apple Prices, dtype: float64


As demonstrated, we can use logical operators like & (and), | (or) and ~ (not) to group multiple conditions.

###**Summary**
Here we have introduced NumPy and Pandas for scientific computing in Python. In the next chapter, we will dive into Pandas to learn resampling and manipulating Pandas DataFrame, which are commonly used in financial data analysis.